name: Android API Test
on:
  workflow_dispatch: # Manual trigger
  pull_request:

jobs:
  android-check-metadata:
    name: Check app metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            repository: organicmaps/api-android
            ref: master
            path: ./
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
            java-version: 17
            distribution: 'temurin'
      - name: Generate release build
        run: ./gradlew assemble
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app_release
          path: app/build/outputs/apk/release/*
