---
name: CI

on:
  workflow_dispatch:

env:
  JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64  # Java 17 is required for Android Gradle 8 plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v3
          with:
            repository: Jean-BaptisteC/organicmaps
            ref: 'download_activity'
            path: ./
        - name: Update dependencies
          shell: bash
          run: |
            sudo apt-get update -y
            sudo apt-get install -y ninja-build
        - name: Configure Java 🔧
          uses: actions/setup-java@v1
          with:
            java-version: 17
        - name: CD 
          run: git submodule update --init --recursive
        - name: Execute script
          run: bash ./configure.sh
        - name: Build Beta
          shell: bash
          working-directory: android
          run: |
            cmake --version
            ninja --version
            gradle -Parm32 assembleFdroidBeta -Pandroidauto=true
        - name: Upload apk
          uses: actions/upload-artifact@v3
          with:
            name: android-FDroidBeta
            path: android/app/build/outputs/apk/**/OrganicMaps-*.apk
            if-no-files-found: error
