name: Generate translations

env:
    DEEPL_FREE_API_KEY: ${{secrets.DEEPL_FREE_API_KEY}}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v4
          with:
            repository: Jean-BaptisteC/organicmaps
            ref: 'linkify_desc'
            path: ./
        - name: Update dependencies
          shell: bash
          run: |
            sudo apt-get update -y
            sudo apt-get install -y ninja-build
        - name: CD 
          run: git submodule update --init --recursive
        - name: Install brew
          run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        - run: brew install translate-shell
        - run: ./tools/python/translate.py Description
