name: Regenerate translations

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v3
          with:
            repository: Jean-BaptisteC/organicmaps
            ref: 'translations'
            path: ./
        - name: Update dependencies
          shell: bash
          run: |
            sudo apt-get update -y
            sudo apt-get install -y ninja-build
        - name: CD 
          run: git submodule update --init --recursive
        - run: ./tools/unix/generate_localizations.sh
        - name: Upload IOS Translations
          uses: actions/upload-artifact@v3
          with:
            name: IOS
            path: iphone/Maps/LocalizedStrings/
        - name: Upload Android Translations
          uses: actions/upload-artifact@v3
          with:
            name: Android
            path: android/res/values*/
